baseURL: https://alirsabet.com/
title: Ali Sabet

defaultContentLanguageInSubdir: true
defaultContentLanguage: fa
languageCode: fa
languageName: فارسی

theme: PaperMod

paginate: 10

enableRobotsTXT: true

disqusShortname: alirsabet

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

permalinks:
  posts: /posts/:year/:month/:slug/
  pages: /:slug/

markup:
  highlight:
    lineNos: true
    style: paraiso-dark
    tabWidth: 4