baseURL: https://alirsabet.com/
title: Ali Sabet

defaultContentLanguageInSubdir: true
defaultContentLanguage: fa
languageCode: fa
languageName: فارسی

theme: PaperMod

pagination:
  pagerSize: 10

googleAnalytics: G-D418BHEZXR

enableRobotsTXT: true

disqusShortname: alirsabet

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

permalinks:
  posts: /posts/:year/:month/:slug/
  pages: /:slug/

markup:
  highlight:
    lineNos: true
    style: paraiso-dark
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

# Move social links (example) here:
params:
  social:
    - name: twitter
      url: https://twitter.com/yourhandle
    - name: github
      url: https://github.com/yourhandle