title: علی ثابت
description: مهندس نرم‌افزار در اکوسیستم Dotnet، علاقه‌مند به AI
author: علی ثابت
homeInfoParams:
  Title: علی ثابت
  Content: مهندس نرم‌افزار در اکوسیستم Dotnet، علاقه‌مند به AI

editPost:
  URL: "https://github.com/hialisabet/blog/tree/main/content"
  Text: "پیشنهاد اصلاح متن"
  appendFilePath: true