env: production
title: Ali Sabet
description: .NET developer with a heart for AI, coding love stories between data and algorithms
author: Ali Sabet

rssFullContent: true

ShowReadingTime: true
ShowShareButtons: true
ShareButtons: ["linkedin", "twitter", "whatsapp", "telegram"]
ShowToc: true
comments: false
defaultTheme: auto
disableSpecial1stPost: true
DateFormat: "2006-01-02"

homeInfoParams:
  Title: Ali Sabet
  Content: .NET developer with a heart for AI, coding love stories between data and algorithms

socialIcons:
  - name: linkedin
    url: https://linkedin.com/in/hialisabet/
  - name: github
    url: https://github.com/hialisabet/
  - name: letterboxd
    url: https://letterboxd.com/hialisabet/
  - name: goodreads
    url: https://goodreads.com/hialisabet/
  - name: twitter
    url: https://twitter.com/hialisabet/
  - name: telegram
    url: https://hialisabet.t.me/
  - name: instagram
    url: https://instagram.com/hialisabet/
  - name: email
    url: mailto:hialisabet+blog@gmail.com
  - name: rss
    url: https://alirsabet.com/fa/index.xml