env: production
title: Ali Sabet
description: .NET developer with a heart for AI
author: Ali Sabet

rssFullContent: true

ShowReadingTime: true
ShowShareButtons: true
ShareButtons: ["linkedin", "twitter", "whatsapp", "telegram"]
ShowCodeCopyButtons: true
ShowToc: true
TocOpen: false
comments: true
defaultTheme: auto
disableSpecial1stPost: true
DateFormat: "2006-01-02"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

homeInfoParams:
  Title: Ali Sabet
  Content: .NET developer with a heart for AI

editPost:
  URL: "https://github.com/alirsabet/blog/tree/main/content"
  Text: "Suggest Changes"
  appendFilePath: true

# for search
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]

socialIcons:
  - name: linkedin
    url: https://linkedin.com/in/alirsabet/
  - name: github
    url: https://github.com/alirsabet/
  - name: letterboxd
    url: https://letterboxd.com/hialisabet/
  - name: goodreads
    url: https://goodreads.com/hialisabet/
  - name: twitter
    url: https://twitter.com/alirsabet/
  - name: telegram
    url: https://alirsabet.t.me/
  - name: email
    url: mailto:hialisabet+blog@gmail.com
  - name: rss
    url: https://alirsabet.com/en/index.xml
