baseURL = "https://alisabet/"
title = "علی ثابت"
theme = "PaperMod"
defaultContentLanguage = "fa"

[languages]
  [languages.fa]
    contentDir = "content/fa"
    languageName = "فارسی"
    weight = 1

  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 2

# Enable the Language Selector Toggle Button
[params]
  enableLanguageSelector = true